### ISSUE TITLE
Hello there can u please put in asian shows in this app too?

### ISSUE THREAD

**Issue by Aruraka** [Masquerade555/Frofter-Anime-App#1]

**Comment by Frofter** [comment]
Hi there @Aruraka, i would love to do that but i won't because I dedicated this app only to anime. 
Although maybe I'll make another app for both Android and IOS which will have these asian shows 🤔

Can you recommend a website which have a huge library of asian shows?
Because when I'll make it i have to check its data/content and make the app accordingly.

**Comment by Aruraka** [comment]
> Hi there @Aruraka, i would love to do that but i won't because I dedicated this app only to anime. Although maybe I'll make another app for both Android and IOS which will have these asian shows 🤔
> 
> Can you recommend a website which have a huge library of asian shows? Because when I'll make it i have to check its data/content and make the app accordingly.

Ok thanks so much there r many..like kissasian , kisskh etc but not dramacool as dramacool subtitles r mostly overlapping that's why .. btw u have discord? So that u can inform me there when u finish making that one with asian dramas?

**Comment by Frofter** [comment]
> > Hi there @Aruraka, i would love to do that but i won't because I dedicated this app only to anime. Although maybe I'll make another app for both Android and IOS which will have these asian shows 🤔
> > 
> > Can you recommend a website which have a huge library of asian shows? Because when I'll make it i have to check its data/content and make the app accordingly.
> 
> Ok thanks so much there r many..like kissasian , kisskh etc but not dramacool as dramacool subtitles r mostly overlapping that's why .. btw u have discord? So that u can inform me there when u finish making that one with asian dramas?

Ok I'll look into those websites it might take some time because currently i have other projects that i have to complete.
And as for social media i only use Instagram which you can find in my github bio. 👍

**Comment by Aruraka** [comment]
> > > Hi there @Aruraka, i would love to do that but i won't because I dedicated this app only to anime. Although maybe I'll make another app for both Android and IOS which will have these asian shows 🤔
> > > Can you recommend a website which have a huge library of asian shows? Because when I'll make it i have to check its data/content and make the app accordingly.
> > 
> > 
> > Ok thanks so much there r many..like kissasian , kisskh etc but not dramacool as dramacool subtitles r mostly overlapping that's why .. btw u have discord? So that u can inform me there when u finish making that one with asian dramas?
> 
> Ok I'll look into those websites it might take some time because currently i have other projects that i have to complete. And as for social media i only use Instagram which you can find in my github bio. 👍

Okay sure thanks 😊
