### ISSUE TITLE
stuck on loading

### ISSUE THREAD

**Issue by Parasgaming122** [Masquerade555/Frofter-Anime-App#2]
![image](https://github.com/user-attachments/assets/94c37379-bcb2-41f5-9949-2f32dfecc964)

**Comment by Parasgaming122** [comment]
i am using wsa(windows subsystem for android)

**Comment by Frofter** [comment]
I never tried my app on this WSA thing but i can think of some issues:

1) The server was updating at that moment
2) If the app still don`t work it would probably mean it can`t work on that WSA (which is i know weird and unusual and shouldn`t happen

It was posted a week ago so i can`t remember :)
