### ISSUE TITLE
Server connecting issues 

### ISSUE THREAD

**Issue by SouljaBoyNy** [Masquerade555/Frofter-Anime-App#5]
When i go to change the server because it says check ur internet and try again it won't allow me to stay connected to the other servers as in when I change the server and push the connect button it says it connected to server 2 but when I back out and go back to the servers it's back on the the original server which is server 3 

please help

**Comment by Frofter** [comment]
Hi there @SouljaBoyNy Thanks for reporting the issue.

1st of all we just have to say that server 2 isn't working for quite some days now only server 1 & 3 are currently working.

And as for your changing server we'll look into it, if its an issue inside the app we will try to fix it as soon as possible.

And as for the message "Check Your Internet" it shows on some of these conditions:
1- When your wifi/mobile data is off
2- When your wifi/mobile data is connected but there is no internet (means you're connected to LAN but not WAN)
3- Server is working but not responding to your requests (which is extremely rare case)

Also remember when you launch our app it automatically connects to the working server.
